export const ErrorCode = {
    // Auth
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_INVALID: 'TOKEN_INVALID',
    REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

    // Resource
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    USER_NOT_VERIFIED: 'EMAIL_ALREADY_EXISTS',

    // Organization / membership
    ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
    MEMBERSHIP_NOT_ACTIVE: 'MEMBERSHIP_NOT_ACTIVE',
    INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
    ORGANIZATION_NOT_SELECTED: 'ORGANIZATION_NOT_SELECTED',

    // Generic
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    UNAUTHORIZED: 'UNAUTHORIZED',
    BAD_REQUEST: 'BAD_REQUEST',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    INTERNAL: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];